### PR TITLE
Generate onError event for <img>

### PR DESCRIPTION
**Pull request by fsoikin**

### CODE REVIEW

**Review by mcordova47 — APPROVED** [review]
Looks good — side note: was wondering why all the codegen instead of extensible records and type aliases. But I haven't thought _too_ much about it, so maybe I'm missing something obvious.

**Comment by fsoikin** [comment]
That would be a question for @gasi

**Comment by gasi** [comment]
> @mcordova47 …was wondering why all the codegen instead of extensible records and type aliases. But I haven't thought _too_ much about it, so maybe I'm missing something obvious.

Can you elaborate on this? You mean reducing code size by sharing common HTML attributes? To be honest, I haven’t thought about it too much either. I wanted us to be able to write MyCV views using PS and adopted what they did in `purescript-react-basic`.

**Comment by mcordova47** [comment]
@gasi — got it, it didn't mean anything about code size. I was just wondering what the benefit of generating the PS code in JS was. I mentioned extensible records because I assumed that the purpose of the codegen was to avoid duplicating a bunch of stuff, and I figured you could do the same in PS.

The context I was missing, though, was that this was based on what `purescript-react-basic` does. Thanks!

**Comment by fsoikin** [comment]
Yes @mcordova47 you are right: it is very possible to translate the JS/JSON files directly into PS partial records. I was going to do it at some point, just as an exercise, but it's not pressing by any means.

**Pull request merged**
